<?php
$title = 'Money';
$this->headTitle($title);
$role = $this->layout()->role;
?>
<div class="PaymentTable">
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="YandexMoney">
                        <a href="/money/yandexmoney/index">
                            <img src="/img/money/yandex_money_payment.png" alt="Yandex Money"/>
                        </a>
                    </div>
                </td>
                <td>
                    <div class="WebMoney">
                        <a href="/money/webmoney/index">
                            <img src="/img/money/webmoney_payment.png" alt="Web Money"/>
                        </a>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="PaypalMoney">
                        <a href="/money/paypal/index">
                            <img src="/img/money/paypal_payment.png" alt="PayPal"/>
                        </a>
                    </div>
                </td>
                <td>
                    <div class="MoneyBookers">
                        <a href="/money/moneybookers/index">
                            <img src="/img/money/money_bookers_payment.png" alt="MoneyBookers"/>
                        </a>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="QiwiWallet">
                        <a href="/money/qiwiwallet/index">
                            <img src="/img/money/qiwi_payment.png" alt="Qiwi Wallet"/>
                        </a>
                    </div>
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        </tbody>
    </table>
</div>