<?php
$title = 'Edit Message';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('dashboard/messages', array(
        'action' => 'edit',
        'id' => $message->id,
        )));
$form->get('submit')->setAttribute('value', 'Update');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('message'));
echo $this->formSubmit($form->get('submit'));
echo $this->formReset($form->get('reset'));
echo $this->form()->closeTag();