<?php
namespace Audio\Controller;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-01 at 17:53:58.
 */
class UploadControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UploadController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UploadController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Audio\Controller\UploadController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Controller\UploadController::uploadAction
     * @todo   Implement testUploadAction().
     */
    public function testUploadAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Controller\UploadController::approveAction
     * @todo   Implement testApproveAction().
     */
    public function testApproveAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Controller\UploadController::deleteAction
     * @todo   Implement testDeleteAction().
     */
    public function testDeleteAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Controller\UploadController::clearAction
     * @todo   Implement testClearAction().
     */
    public function testClearAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
