<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Z2T - Admin Page') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand mybrand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('My Project') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Statistic') ?></a></li>
                        </ul>
                        <ul class="nav">
                            <li><a href="<?php echo $this->url('admin/adminmanage') ?>"><?php echo $this->translate('Admins') ?></a></li>
                        </ul>
                        <ul class="nav">
                            <li><a href="<?php echo $this->url('admin/usermanage') ?>"><?php echo $this->translate('Users') ?></a></li>
                        </ul>
                        <ul class="nav">
                            <li><a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logs') ?></a></li>
                        </ul>
                        <ul class="nav">
                            <li><a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('MongoDb') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                    <?php if(isset($auth)){ ?>
                        <a class="btn btn-warning logout-btn" href="<?php echo $this->url('logout') ?>">Logout</a>
                        <span class="current-user <?= ($role == 'admin') ? ' admin' : ''; ?>"><?= $auth->fullName; ?></span>
                    <?php }  else { ?>
                        <a class="btn btn-info logout-btn" href="<?php echo $this->url('userauth') ?>">Login</a>
                    <?php } ?>
                </div>
                
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                Footer Place
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>