<?php
$title = 'Delete uploaded file';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($entry->filename); ?>'
</p>
<?php
$url = $this->url('storage', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $entry->id; ?>" />
    <input class="btn btn-danger" type="submit" name="delete" value="Yes" />
    <input class="btn" type="submit" name="delete" value="No" />
</div>
</form>