<?php

$title = 'Edit audio information';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml('Edit information about audio track'); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('audio', array(
    'action' => 'edit',
    'id' => $this->id,
    )));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formRow($form->get('filename'));
echo $this->formSubmit($form->get('submit'));
echo $this->formReset($form->get('reset'));
echo $this->form()->closeTag();
?>
