<?php

$this->headTitle('Delete User');
?>
<h1><?php echo $this->escapeHtml('Delete current user from Dashboard'); ?></h1>
 
<p>Are you sure that you want to delete current user <?= $user->login; ?> from DashBoard ?</p>
<?php
$url = $this->url('dashboard/user', array(
    'action' => 'delete',
    'id'     => $user->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
    <input class="btn btn-danger" type="submit" name="delete" value="Yes" />
    <input class="btn" type="submit" name="delete" value="No" />
</div>
</form>