<?php
$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('dashboard/user', array(
        'action' => 'edit',
        'id' => $user->id,
        )));
$form->prepare();

echo $this->form()->openTag($form);
?> <div class="zend-form-right"> <?php
echo $this->formHidden($form->get('id'));
echo $this->formLabel($form->get('login'));
echo $this->formText($form->get('login'));
echo $this->formLabel($form->get('email'));
echo $this->formText($form->get('email'));
echo $this->formLabel($form->get('fullname'));
echo $this->formText($form->get('fullname'));
?> </div> <?php
echo $this->formSubmit($form->get('submit'));
echo $this->formReset($form->get('reset'));
echo $this->form()->closeTag();

$messages = $form->getMessages();
if ($messages) {
    ?>
        <div class="error-panel">
            <?php foreach ($messages as $elementName => $errors) {
                $label = $this->formLabel($form->get($elementName));
                foreach ($errors as $error) {
                    echo $label;
                    ?>
                                <p class="text-error"><?= $error ?><p/>
            <?php
        }
    }
    ?>
                </div>
    <?php
}