<?php
$title = 'DashBoard Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-success" href="<?php echo $this->url('dashboard/user', array('action' => 'add')); ?>">Add new user</a>
</p>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Login</th>
        <th>Email</th>
        <th>Full Name</th>
        <th>Pasword</th>
        <th class="datetime-th">Created</th>
        <th class="datetime-th">Last Login</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->id); ?></td>
            <td><?php echo $this->escapeHtml($user->login); ?></td>
            <td><?php echo $this->escapeHtml($user->email); ?></td>
            <td><?php echo $this->escapeHtml($user->fullName); ?></td>
            <td><a class="btn btn-small btn-warning" href="<?php echo $this->url('dashboard/user', array('action' => 'changepass', 'id' => $user->id)); ?>">Change Password</a></td>
            <td><?php echo $user->created->format('H:i d-M-Y'); ?></td>
            <td><?php echo $user->lastLogin->format('H:i d-M-Y'); ?></td>
            <td>
                <a class="btn btn-small btn-info" href="<?php echo $this->url('dashboard/user', array('action' => 'edit', 'id' => $user->id)); ?>">Edit</a>
                <a class="btn btn-small btn-danger" href="<?php echo $this->url('dashboard/user', array('action' => 'delete', 'id' => $user->id)); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>