<?php
$title = 'My Project Admins';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-warning" href="<?php echo $this->url('admin/adminmanage', array('action' => 'add')); ?>">Add new admin</a>
</p>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Login</th>
        <th>Email</th>
        <th>Full Name</th>
        <th>Pasword</th>
        <th class="datetime-th">Created</th>
        <th class="datetime-th">Last Login</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <?php foreach ($admins as $admin) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($admin->id); ?></td>
            <td><?php echo $this->escapeHtml($admin->login); ?></td>
            <td><?php echo $this->escapeHtml($admin->email); ?></td>
            <td><?php echo $this->escapeHtml($admin->fullName); ?></td>
            <td><a class="btn btn-small btn-warning" href="<?php echo $this->url('admin/adminmanage', array('action' => 'changepass', 'id' => $admin->id)); ?>">Change Password</a></td>
            <td><?php echo $admin->created->format('H:i d-M-Y'); ?></td>
            <td><?php echo $admin->lastLogin->format('H:i d-M-Y'); ?></td>
            <td>
                <a class="btn btn-small btn-info" href="<?php echo $this->url('admin/adminmanage', array('action' => 'edit', 'id' => $admin->id)); ?>">Edit</a>
                <a class="btn btn-small btn-danger" href="<?php echo $this->url('admin/adminmanage', array('action' => 'delete', 'id' => $admin->id)); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>