<?php
 
$title = 'Search albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'index'));?>">My albums</a>
</p>

<?php if (isset($albums)) : ?>
    <table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title); ?></td>
            <td><?php echo $this->escapeHtml($album->artist); ?></td>
            <td>
                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id));
        ?>">Edit</a>
                <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif; ?>
<?php
$url = $this->url('album', array(
    'action' => 'search',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <label for="query">Input search condition: </label>
    <input type="text" name="query"/>
    <input type="submit" name="submit" value="Ok"/>
</div>
</form>