<?php

$this->headTitle('Logout');
?>
<h1><?php echo $this->escapeHtml('Logout from Dashboard system'); ?></h1>
 
<p>Are you sure that you want to logout current user '<?= $user->fullName; ?>' from DashBoard ?</p>
<form action="<?php $this->url('logout'); ?>" method="post">
<div>
    <input class="btn btn-warning" type="submit" name="logout" value="Yes" />
    <input class="btn btn-success" type="submit" name="logout" value="No" />
</div>
</form>