<?php
namespace Audio\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-02 at 10:36:28.
 */
class TemporyStorageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TemporyStorage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TemporyStorage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Audio\Model\TemporyStorage::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Model\TemporyStorage::countTemporyImages
     * @todo   Implement testCountTemporyImages().
     */
    public function testCountTemporyImages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Model\TemporyStorage::addFile
     * @todo   Implement testAddFile().
     */
    public function testAddFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Model\TemporyStorage::getEntry
     * @todo   Implement testGetEntry().
     */
    public function testGetEntry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Model\TemporyStorage::deleteEntry
     * @todo   Implement testDeleteEntry().
     */
    public function testDeleteEntry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Audio\Model\TemporyStorage::clearAll
     * @todo   Implement testClearAll().
     */
    public function testClearAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
